/* Geography for the situation map.

   The outlines are real. They come from Natural Earth (public domain), clipped
   to the frames this map can actually show and generalised per region — see
   coastlines.js, which is generated by .design/build-coastlines.py.

   They used to be hand-drawn polygons, seventeen points for Cuba and thirty
   for the whole of Eurasia, on the reasoning that the map's job was to show
   the four poles of the crisis rather than to be an atlas. That was true and
   still produced a Cuba nobody could identify as Cuba, which undercut the one
   thing the map exists to make concrete. A shape a student cannot recognise
   cannot carry a fact about distance.

   The range rings are accurate for the same reason: they are computed by
   walking a true great-circle bearing around the launch point, so their shape
   reflects the real projected footprint rather than a drawn ellipse. */

import { COASTLINES, LAKES } from './coastlines.js';

/* Equirectangular projection. Simple, and honest about being a projection. */
export const project = (lon, lat, frame) => ({
  x: ((lon - frame.lon0) / (frame.lon1 - frame.lon0)) * frame.width,
  y: ((frame.lat1 - lat) / (frame.lat1 - frame.lat0)) * frame.height,
});

/* Frame dimensions are DERIVED, not chosen.

   All three frames used to be 1000x520 whatever ground they covered, which
   made the Caribbean frame stretch everything horizontally by a factor of
   1.8: Cuba was drawn very nearly twice as wide as it is, and the range rings
   — the one part of this map whose numbers are exact — were displayed as wide
   ellipses when a great-circle radius near its own centre should read as
   close to a circle.

   So each height is computed from its span such that a degree of longitude
   and a degree of latitude cover the same distance on screen at the frame's
   mid-latitude. That is the equidistant cylindrical projection with a
   standard parallel through the middle of what you are looking at, and it is
   the reason the shapes are now the shapes. The SVG is `width: 100%; height:
   auto`, so the panels follow. */
export const FRAMES = {
  /* A wide strip, because 180 degrees of longitude honestly proportioned is a
     wide strip. Standard parallel 34N. */
  hemispheric: { lon0: -128, lon1: 52, lat0: -6, lat1: 74, width: 1000, height: 368 },
  /* Declared but not currently rendered anywhere — the panel shows the
     hemispheric frame and switches to `regional` on inspection. Kept because
     it is the natural frame for a Caribbean close-up and costs nothing but
     these four lines. Widened from 36 degrees of longitude to 48: at the old
     span, correct proportions would have made it taller than it is wide.
     Standard parallel 29N. */
  caribbean: { lon0: -100, lon1: -52, lat0: 14, lat1: 44, width: 1000, height: 547 },
  /* The frame the range rings are drawn in. A 1,290-mile radius is roughly 19
     degrees of arc, which overflows the Caribbean frame entirely and renders
     as a wash of colour rather than as a ring. This frame is sized so the
     MRBM ring sits inside it and the IRBM ring runs off the edge — which is
     itself the point worth seeing. Standard parallel 28N. */
  regional: { lon0: -128, lon1: -30, lat0: -4, lat1: 60, width: 1000, height: 577 },
};

/* The four poles of the crisis. */
export const MARKERS = [
  { id: 'washington', label: 'Washington', lon: -77.04, lat: 38.9, anchor: 'end', frames: ['hemispheric', 'caribbean', 'regional'] },
  { id: 'new-york', label: 'United Nations', sub: 'New York', lon: -73.97, lat: 40.75, frames: ['hemispheric', 'caribbean', 'regional'] },
  { id: 'moscow', label: 'Moscow', lon: 37.62, lat: 55.75, frames: ['hemispheric'] },
  { id: 'havana', label: 'Havana', lon: -82.38, lat: 23.13, frames: ['caribbean'] },
  { id: 'san-cristobal', label: 'San Cristóbal', sub: 'Missile site', lon: -83.05, lat: 22.72, site: true, frames: ['hemispheric', 'caribbean', 'regional'] },
];

const EARTH_RADIUS_MI = 3958.8;
const toRad = (deg) => (deg * Math.PI) / 180;
const toDeg = (rad) => (rad * 180) / Math.PI;

/* Destination point at a given great-circle distance and bearing. */
function destination(lon, lat, distanceMi, bearingDeg) {
  const delta = distanceMi / EARTH_RADIUS_MI;
  const theta = toRad(bearingDeg);
  const phi1 = toRad(lat);
  const lambda1 = toRad(lon);

  const phi2 = Math.asin(
    Math.sin(phi1) * Math.cos(delta) + Math.cos(phi1) * Math.sin(delta) * Math.cos(theta),
  );
  const lambda2 =
    lambda1 +
    Math.atan2(
      Math.sin(theta) * Math.sin(delta) * Math.cos(phi1),
      Math.cos(delta) - Math.sin(phi1) * Math.sin(phi2),
    );

  return { lon: toDeg(lambda2), lat: toDeg(phi2) };
}

/* A true range ring, as a projected polygon. */
export function rangeRing(lon, lat, distanceMi, frame, steps = 180) {
  const points = [];
  for (let i = 0; i <= steps; i += 1) {
    const bearing = (i / steps) * 360;
    const point = destination(lon, lat, distanceMi, bearing);
    points.push(project(point.lon, point.lat, frame));
  }
  return points;
}

/* The two missile types emplaced or en route in October 1962.

   A note on the numbers, because they are the figures most likely to be
   remembered from this screen. The 1962 briefing charts marked their arcs at
   1,020 and 2,200 NAUTICAL miles. Those same numbers are widely repeated as
   statute miles, which is wrong by a wide enough margin to matter: Washington
   lies 1,173 statute miles from San Cristóbal, so a 1,100-statute-mile arc
   would place the capital outside MRBM range and invert the entire point of
   the map. The values below are the missiles' published ranges in kilometres,
   converted. */
export const RANGE_RINGS = [
  {
    id: 'mrbm',
    label: 'SS-4 MRBM',
    detail: 'R-12',
    distanceMi: 1292, // 2,080 km
    note: '2,080 km · approx. 1,290 miles',
  },
  {
    id: 'irbm',
    label: 'SS-5 IRBM',
    detail: 'R-14',
    distanceMi: 2796, // 4,500 km
    note: '4,500 km · approx. 2,800 miles',
  },
];

export const LAUNCH_POINT = { lon: -83.05, lat: 22.72 };

/* A frame as a lon/lat box, for deciding what can possibly be on screen. */
const frameBox = (frame) => [frame.lon0, frame.lat0, frame.lon1, frame.lat1];

const overlaps = (b, box) =>
  !(b[2] < box[0] || b[0] > box[2] || b[3] < box[1] || b[1] > box[3]);

/* Project one ring of flat [lon, lat, lon, lat, ...] into an SVG path.

   Written as a loop over a flat array rather than a map over pairs because
   this runs across roughly five thousand points every time the frame changes,
   and the pair form allocated an array per point to do it. */
const ringToPath = (coords, frame) => {
  let d = '';
  for (let i = 0; i < coords.length; i += 2) {
    const x = ((coords[i] - frame.lon0) / (frame.lon1 - frame.lon0)) * frame.width;
    const y = ((frame.lat1 - coords[i + 1]) / (frame.lat1 - frame.lat0)) * frame.height;
    d += `${i ? 'L' : 'M'}${x.toFixed(1)} ${y.toFixed(1)}`;
  }
  return `${d}Z`;
};

/* What to draw for a given frame.

   Rings whose bounding box cannot intersect the frame are skipped rather than
   projected and clipped by the viewport — at hemispheric scale that is most of
   the Arctic archipelago, and in the Caribbean frame it is everything except a
   handful of islands and the Gulf coast. */
export const landFor = (frame) => {
  const box = frameBox(frame);
  const out = [];
  for (let i = 0; i < COASTLINES.length; i += 1) {
    const ring = COASTLINES[i];
    if (!overlaps(ring.b, box)) continue;
    out.push({ key: ring.id ?? `c${i}`, id: ring.id, d: ringToPath(ring.c, frame) });
  }
  return out;
};

export const lakesFor = (frame) => {
  const box = frameBox(frame);
  const out = [];
  for (let i = 0; i < LAKES.length; i += 1) {
    const lake = LAKES[i];
    if (!overlaps(lake.b, box)) continue;
    out.push({ key: `l${i}`, d: ringToPath(lake.c, frame) });
  }
  return out;
};

export const ringPath = (points) =>
  `M ${points.map((p) => `${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' L ')} Z`;
